#!/bin/bash

# 🚀 Automated Deployment Script for OrionMaps
# This script will help you deploy your backend to Render

echo "🚀 OrionMaps Backend Deployment Helper"
echo "======================================="
echo ""

# Check if render.yaml exists
if [ ! -f "render.yaml" ]; then
    echo "❌ Error: render.yaml not found!"
    exit 1
fi

echo "📋 Before deploying, make sure you have:"
echo ""
echo "1. ✅ Neo4j Aura database (you already have this)"
echo "   URI: neo4j+s://f579f98d.databases.neo4j.io"
echo ""
echo "2. ⚠️  Upstash Redis - Create free account at https://upstash.com"
echo "   - Sign up with Google/GitHub"
echo "   - Create a new database"
echo "   - Copy the Redis URL (looks like: redis://default:xxx@xxx.upstash.io:6379)"
echo ""
echo "3. ⚠️  Render account - Sign up at https://render.com"
echo "   - Use your GitHub account to sign in"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 DEPLOYMENT STEPS:"
echo ""
echo "1. Push this code to GitHub:"
echo "   git add render.yaml deploy-backend.sh"
echo "   git commit -m 'Add Render deployment config'"
echo "   git push"
echo ""
echo "2. Go to https://dashboard.render.com/select-repo?type=blueprint"
echo ""
echo "3. Connect your GitHub repository: parthpalav/BigD"
echo ""
echo "4. Render will detect render.yaml and set up your service"
echo ""
echo "5. Fill in the environment variables marked 'sync: false':"
echo "   - SECRET_KEY: ER33wipP7QrQf4NFIheoDiHb"
echo "   - JWT_SECRET: a9F3kP2X7M4R8eCqWJ6YBvT5ZsNnHUmL"
echo "   - NEO4J_URI: neo4j+s://f579f98d.databases.neo4j.io"
echo "   - NEO4J_PASSWORD: BigData2025"
echo "   - REDIS_URL: [Get from Upstash]"
echo "   - GOOGLE_CLIENT_ID: [From server/.env]"
echo "   - GOOGLE_CLIENT_SECRET: [From server/.env]"
echo "   - FEATHERLESS_API_KEY: [From server/.env]"
echo "   - FAST2SMS_API_KEY: [From server/.env]"
echo "   - WHATSAPP_BUSINESS_TOKEN: [From server/.env]"
echo "   - WHATSAPP_PHONE_NUMBER_ID: [From server/.env]"
echo ""
echo "6. Click 'Apply' to deploy"
echo ""
echo "7. Wait 3-5 minutes for deployment"
echo ""
echo "8. You'll get a URL like: https://orionmaps-api.onrender.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔄 AFTER BACKEND IS DEPLOYED:"
echo ""
echo "Run: ./update-frontend.sh <your-backend-url>"
echo "Example: ./update-frontend.sh https://orionmaps-api.onrender.com"
echo ""
echo "This will update the frontend and redeploy it."
echo ""
