#!/bin/bash

# Update frontend with backend URL and redeploy

if [ -z "$1" ]; then
    echo "❌ Error: Backend URL required"
    echo "Usage: ./update-frontend.sh <backend-url>"
    echo "Example: ./update-frontend.sh https://orionmaps-api.onrender.com"
    exit 1
fi

BACKEND_URL="$1"

echo "🔄 Updating frontend configuration..."
echo "Backend URL: $BACKEND_URL"

# Update client/.env.production
cat > client/.env.production << EOF
# Production Environment Variables
# Auto-generated by update-frontend.sh

# Backend API URL
VITE_API_URL=${BACKEND_URL}/api/v1

# Google OAuth Configuration
VITE_GOOGLE_CLIENT_ID=371636086652-mg4agd7veafvi0ppqthq7ut9b12jj0je.apps.googleusercontent.com

# Mapbox Token (optional)
# VITE_MAPBOX_TOKEN=your_mapbox_token_here
EOF

echo "✅ Updated client/.env.production"
echo ""
echo "📦 Building frontend..."

cd client && npm run build && cd ..

echo ""
echo "🚀 Deploying to Firebase..."

firebase deploy --only hosting

echo ""
echo "✅ Deployment complete!"
echo ""
echo "Your app is now live at:"
echo "🌐 https://orion-81736.web.app"
echo ""
echo "⚠️  Don't forget to update Google OAuth settings:"
echo "1. Go to https://console.cloud.google.com/apis/credentials"
echo "2. Add these to Authorized JavaScript origins:"
echo "   - https://orion-81736.web.app"
echo "   - ${BACKEND_URL}"
echo "3. Add to Authorized redirect URIs:"
echo "   - https://orion-81736.web.app/auth/google/callback"
echo ""
